### ISSUE TITLE
SPICEBodies Comments

### ISSUE THREAD

**Issue by andrew-saydjari** [JuliaAstro/EphemerisSources.jl#15]
- [x] (Probably a feature request) It would be much better if the result of the KernelBody type on an epoch was a named tuple, which could have DataFrames support like HorizonsEphemeris, rather that a Vector{Vector{}} because that is fairly opaque. I think it would not take *that* much effort to do this, but I will also view this comment as not being an acceptance-blocker.

**Comment by jdc-pub** [comment]
The `(::KernelBody)(...)` method now outputs a named tuple, which is directly compatible with `StaticArrays.FieldVector` sub-types, `DataFrames`, `CSV`, and more! I have noticed that `NamedTuple` types are really performant when constructing `FieldVector` types, as I do in [`AstrodynamicalModels.jl`](https://github.com/cadojo/GeneralAstrodynamics.jl/blob/c2f5def232ca511bcae8a241e16044690db2d13e/lib/AstrodynamicalModels/src/AstrodynamicalModels.jl#L143).

**Comment by andrew-saydjari** [comment]
While trying to check this, I hit.

```
⌅ [8e9d28ce] SPICEKernels v1.4.4 (<v2.0.0): EphemerisSources
```

Seems like some compat to fix. I am not sure if your compat helper in the outer directory is managing the subpackages correctly.

**Comment by andrew-saydjari** [comment]
But I was able to successfully confirm that the named tuple output is working. So the above comment is really just to let you know about your compat management. My review of this issue is complete.

**Comment by jdc-pub** [comment]
This should be corrected as of `EphemerisSourcesv0.3`

**Comment by andrew-saydjari** [comment]
Confirmed. Happy with the completion of this issue.
