### ISSUE TITLE
High-Level Comments

### ISSUE THREAD

**Issue by andrew-saydjari** [JuliaAstro/EphemerisSources.jl#16]
- [x] #37
- [x] You have a nice statement of need on your https://ephemeris.loopy.codes/lib/SPICEKernels/dev/ page, but not on the overview landing page. Adding one on the overview page would be helpful.
- [x] I did not see any community guidelines (which is one of our review checklist items). Please add something that addresses that requirement to help people know how willing you are to interact with them in terms of contributions, issues, and support.
- [x] A single, common, real-world example might be a good addition to the docs. If you showed how to solve it with both the SPICE and Horizons sub packages, that would be amazing. I am trying to understand the best real-world example to use here. I see you have https://github.com/cadojo/GeneralAstrodynamics.jl, so maybe you have an example motivated by that work? Personally, I would care about querying an ephemeris most in the context of knowing how far away an object would be from where my telescope is pointing... but that does not seem to be an easy application/goal of these packages, which are more focused on cartesian coordinates and state vectors. Maybe a "real-world" application is to calculate the closest approach of two objects? What is the minimum distance between Gaia and JWST over the last year? (that is a question I would find at least intriguing)
- [x] You never show an example that uses the velocity information... seems like cooking up and example that uses velocities might be nice.

**Comment by jdc-pub** [comment]
Velocity example posted here: https://juliaastro.org/EphemerisSources.jl/docs/dev/examples/velocity-study/

**Comment by andrew-saydjari** [comment]
Can you point me to where you added guidelines to address?
- [x] I did not see any community guidelines (which is one of our review checklist items). Please add something that addresses that requirement to help people know how willing you are to interact with them in terms of contributions, issues, and support.

**Comment by jdc-pub** [comment]
@andrew-saydjari I had thought the [code of conduct](https://github.com/JuliaAstro/EphemerisSources.jl/blob/main/CODE_OF_CONDUCT.md) was the standard "community guidelines" for projects on GitHub. I'm sure that file is not an issue, but to satisfy this item, should I add something else?

**Comment by andrew-saydjari** [comment]
The exact wording I have is " Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support" My view is that this is different from a code of conduct. Here you are telling the people reading your README.md how you feel about contributions. Some packages have such high use rates that developers cannot respond to every issue or will only respond to PRs passing tests/some formatting restrictions. Some packages are happy to take issues, PRs, bug reports, feature requests, etc. People generally put a sentence at the bottom of the readme to explain their stance on that. See some examples
- https://github.com/SciML/DifferentialEquations.jl, which directs some questions to Gitter, some to issues, and developers to a special part of the documentation.
- https://github.com/andrew-saydjari/CloudCovErr.jl for a minimal example from me... just telling people we know things are still preliminary and are committed to fixing it if they make an issue. 

You can be anywhere on this spectrum of complexity of statement (and also be less open to contributions), but I think the goal of this item on the checklist is to make sure you have said *something* about your position on contributions/issues/etc.

**Comment by jdc-pub** [comment]
Done! See the [README.md](https://github.com/JuliaAstro/EphemerisSources.jl/blob/main/README.md#Contributions).
