### ISSUE TITLE
Meta-package EphemerisSources.jl

### ISSUE THREAD

**Issue by tamasgal** [JuliaAstro/EphemerisSources.jl#17]
I was wondering if it would make sense to create a bare-bone meta package called `EphemerisSources.jl` which includes the four main packages as dependencies with some constraints on versions to make sure they play well together.

**Comment by jdc-pub** [comment]
I have added `EphemerisSources.jl` and `EphemerisSourcesBase.jl`. I would like to add types for interfaces which would be added to `EphemerisSources.jl` too, but I haven't quite figured out what types and methods would work best, so I'd like that to be a `v2` milestone for this (small) project. I hope that's acceptable for this paper!

**Comment by tamasgal** [comment]
Sorry, this issue slipped through my notifications. Yes very nice!
