### ISSUE TITLE
Move to @JuliaAstro

### ISSUE THREAD

**Issue by jdc-pub** [JuliaAstro/EphemerisSources.jl#25]
@helgee This project provides ephemeris wrappers for JPL Horizons and generic SPICE kernels. It's  a relatively new project, but the core features are here, and it is under review for the Journal of Open Source Software. I'd be interested in moving this project to the @JuliaAstro organization. I'm a member, but I wanted to ask first. What do you think?

**Comment by jdc-pub** [comment]
@helgee I moved this project to @JuliaAstro. If you approve, could you please enable `gh-pages`?

**Comment by helgee** [comment]
Pinging @giordano: I will promote @cadojo to owner if there are no objections.

**Comment by giordano** [comment]
I made @cadojo admin of the repo, it's a bit annoying github doesn't do that automatically for transfers.
