### ISSUE TITLE
Codecov Integration

### ISSUE THREAD

**Issue by jdc-pub** [JuliaAstro/EphemerisSources.jl#37]

**Comment by andrew-saydjari** [comment]
Did you want to add the badge (https://app.codecov.io/gh/JuliaAstro/EphemerisSources.jl) to your readme?

**Comment by jdc-pub** [comment]
Done!

**Comment by jdc-pub** [comment]
The coverage is quite low... I have work to do to add tests. But the coverage is certainly artificially low due to the autogenerated codes in `SPICEKernels` which are not tested, because they are tested at "autogeneration" time.

**Comment by andrew-saydjari** [comment]
Thanks. If you have good reason to exclude certain files, for reasons like you outlined, you can feel free too add a yaml file that excludes those line to fix this "artificial" decrease. See for example when I did this https://github.com/andrew-saydjari/apMADGICS.jl/blob/main/.github/codecov.yml
